import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>tauri-next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className="text-6xl">tauri-next</h1>
        <p>
          Prise en main de <pre style={{ display: "inline" }}>Tauri</pre>, une
          librairie qui permet de créer des applications desktop avec des
          technologies web (ici : Nextjs)
        </p>
        <button>
          <Link href="/async">Traitement asynchrones</Link>
        </button>
      </main>
    </>
  );
}
